# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'UNIP Plus Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UNIP Plus Example
  pod 'UPComponents', :path => '../'

  target 'UNIP Plus Example Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
